name: Build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build the 'ttr' test tool and SCS Plugin
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64

      - name: Build with MSBuild commandline tool
        run: msbuild /p:Configuration=Release /t:build twinTurboRumbler.sln

      - name: Upload Test tool
        uses: actions/upload-artifact@v3
        with:
          name: CommandlineTestTool
          path: x64/Release/ttr.exe

      - name: Upload the SCS Plugin
        uses: actions/upload-artifact@v3
        with:
          name: ForceRumbleBack_SCS_Plugin
          path: x64/Release/ForceRumbleBack.dll